name: Waka Readme

on:
  schedule:
    # Runs twice daily on weekdays (Monday-Friday) at 6am and 6pm IST
    - cron: '30 0 * * 1-5'   # 6am IST (00:30 UTC)
    - cron: '30 12 * * 1-5'  # 6pm IST (12:30 UTC)
    # Runs 4 times during weekends (Saturday-Sunday) at 6am, 12pm, 6pm, 12am IST
    - cron: '30 0 * * 6,0'   # 6am IST (00:30 UTC)
    - cron: '30 6 * * 6,0'   # 12pm IST (06:30 UTC)
    - cron: '30 12 * * 6,0'  # 6pm IST (12:30 UTC)
    - cron: '30 18 * * 6,0'  # 12am IST (18:30 UTC)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_UPDATED_DATE: "False"
          COMMIT_BY_ME: "True"
          COMMIT_USERNAME: ${{ secrets.GIT_NAME }}
          COMMIT_EMAIL: ${{ secrets.GIT_EMAIL }}